/*
 * This file is generated by jOOQ.
 */
package com.liucan.boot.persist.jooq.amazondata;


import com.liucan.boot.persist.jooq.amazondata.tables.ShopInfo;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>amazon_data</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SHOP_INFO_PRIMARY = Indexes0.SHOP_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SHOP_INFO_PRIMARY = Internal.createIndex("PRIMARY", ShopInfo.SHOP_INFO, new OrderField[]{ShopInfo.SHOP_INFO.ID}, true);
    }
}
