/*
 * This file is generated by jOOQ.
 */
package com.liucan.boot.persist.jooq.amazondata;


import com.liucan.boot.persist.jooq.amazondata.tables.ShopInfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in amazon_data
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * 店铺表
     */
    public static final ShopInfo SHOP_INFO = com.liucan.boot.persist.jooq.amazondata.tables.ShopInfo.SHOP_INFO;
}
