package com.liucan.boot.persist.mybatis.javalearn.mode;

public class CommonUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_user.id
     *
     * @mbg.generated Sun Oct 21 16:10:31 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_user.id
     *
     * @return the value of common_user.id
     * @mbg.generated Sun Oct 21 16:10:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_user.id
     *
     * @param id the value for common_user.id
     * @mbg.generated Sun Oct 21 16:10:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}