/*
 * This file is generated by jOOQ.
 */
package com.liucan.boot.persist.jooq.amazondata.tables.daos;


import com.liucan.boot.persist.jooq.amazondata.tables.ShopInfo;
import com.liucan.boot.persist.jooq.amazondata.tables.records.ShopInfoRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.util.List;


/**
 * 店铺表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ShopInfoDao extends DAOImpl<ShopInfoRecord, com.liucan.boot.persist.jooq.amazondata.tables.pojos.ShopInfo, Integer> {

    /**
     * Create a new ShopInfoDao without any configuration
     */
    public ShopInfoDao() {
        super(ShopInfo.SHOP_INFO, com.liucan.boot.persist.jooq.amazondata.tables.pojos.ShopInfo.class);
    }

    /**
     * Create a new ShopInfoDao with an attached configuration
     */
    public ShopInfoDao(Configuration configuration) {
        super(ShopInfo.SHOP_INFO, com.liucan.boot.persist.jooq.amazondata.tables.pojos.ShopInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.liucan.boot.persist.jooq.amazondata.tables.pojos.ShopInfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.liucan.boot.persist.jooq.amazondata.tables.pojos.ShopInfo> fetchById(Integer... values) {
        return fetch(ShopInfo.SHOP_INFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.liucan.boot.persist.jooq.amazondata.tables.pojos.ShopInfo fetchOneById(Integer value) {
        return fetchOne(ShopInfo.SHOP_INFO.ID, value);
    }

    /**
     * Fetch records that have <code>shop_id IN (values)</code>
     */
    public List<com.liucan.boot.persist.jooq.amazondata.tables.pojos.ShopInfo> fetchByShopId(Integer... values) {
        return fetch(ShopInfo.SHOP_INFO.SHOP_ID, values);
    }

    /**
     * Fetch records that have <code>shop_name IN (values)</code>
     */
    public List<com.liucan.boot.persist.jooq.amazondata.tables.pojos.ShopInfo> fetchByShopName(String... values) {
        return fetch(ShopInfo.SHOP_INFO.SHOP_NAME, values);
    }
}
