/*
 * This file is generated by jOOQ.
 */
package com.liucan.boot.persist.jooq.javalearn.tables.daos;


import com.liucan.boot.persist.jooq.javalearn.tables.CommonUser;
import com.liucan.boot.persist.jooq.javalearn.tables.records.CommonUserRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CommonUserDao extends DAOImpl<CommonUserRecord, com.liucan.boot.persist.jooq.javalearn.tables.pojos.CommonUser, Integer> {

    /**
     * Create a new CommonUserDao without any configuration
     */
    public CommonUserDao() {
        super(CommonUser.COMMON_USER, com.liucan.boot.persist.jooq.javalearn.tables.pojos.CommonUser.class);
    }

    /**
     * Create a new CommonUserDao with an attached configuration
     */
    public CommonUserDao(Configuration configuration) {
        super(CommonUser.COMMON_USER, com.liucan.boot.persist.jooq.javalearn.tables.pojos.CommonUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.liucan.boot.persist.jooq.javalearn.tables.pojos.CommonUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.liucan.boot.persist.jooq.javalearn.tables.pojos.CommonUser> fetchById(Integer... values) {
        return fetch(CommonUser.COMMON_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.liucan.boot.persist.jooq.javalearn.tables.pojos.CommonUser fetchOneById(Integer value) {
        return fetchOne(CommonUser.COMMON_USER.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.liucan.boot.persist.jooq.javalearn.tables.pojos.CommonUser> fetchByName(String... values) {
        return fetch(CommonUser.COMMON_USER.NAME, values);
    }
}
