/*
 * This file is generated by jOOQ.
 */
package com.liucan.boot.persist.jooq.amazondata.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 店铺表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ShopInfo implements Serializable {

    private static final long serialVersionUID = -2126615805;

    private Integer id;
    private Integer shopId;
    private String shopName;

    public ShopInfo() {
    }

    public ShopInfo(ShopInfo value) {
        this.id = value.id;
        this.shopId = value.shopId;
        this.shopName = value.shopName;
    }

    public ShopInfo(
            Integer id,
            Integer shopId,
            String shopName
    ) {
        this.id = id;
        this.shopId = shopId;
        this.shopName = shopName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getShopId() {
        return this.shopId;
    }

    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    public String getShopName() {
        return this.shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShopInfo (");

        sb.append(id);
        sb.append(", ").append(shopId);
        sb.append(", ").append(shopName);

        sb.append(")");
        return sb.toString();
    }
}
