package com.liucan.boot.persist.mybatis.mode;

public class LoggingEventException {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_exception.event_id
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    private Long eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_exception.i
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    private Short i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logging_event_exception.trace_line
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    private String traceLine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_exception.event_id
     *
     * @return the value of logging_event_exception.event_id
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_exception.event_id
     *
     * @param eventId the value for logging_event_exception.event_id
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_exception.i
     *
     * @return the value of logging_event_exception.i
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    public Short getI() {
        return i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_exception.i
     *
     * @param i the value for logging_event_exception.i
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    public void setI(Short i) {
        this.i = i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logging_event_exception.trace_line
     *
     * @return the value of logging_event_exception.trace_line
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    public String getTraceLine() {
        return traceLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logging_event_exception.trace_line
     *
     * @param traceLine the value for logging_event_exception.trace_line
     *
     * @mbg.generated Sat Apr 25 11:46:27 CST 2020
     */
    public void setTraceLine(String traceLine) {
        this.traceLine = traceLine == null ? null : traceLine.trim();
    }
}