package com.liucan.boot.persist.mybatis.mode;

import java.time.LocalDateTime;

public class SystemLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.id
     *
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.type
     *
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.thread_name
     *
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    private String threadName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.class_name
     *
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.create_time
     *
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.id
     *
     * @return the value of system_log.id
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.id
     *
     * @param id the value for system_log.id
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.type
     *
     * @return the value of system_log.type
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.type
     *
     * @param type the value for system_log.type
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.thread_name
     *
     * @return the value of system_log.thread_name
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public String getThreadName() {
        return threadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.thread_name
     *
     * @param threadName the value for system_log.thread_name
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public void setThreadName(String threadName) {
        this.threadName = threadName == null ? null : threadName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.class_name
     *
     * @return the value of system_log.class_name
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.class_name
     *
     * @param className the value for system_log.class_name
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.create_time
     *
     * @return the value of system_log.create_time
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.create_time
     *
     * @param createTime the value for system_log.create_time
     * @mbg.generated Sun Apr 19 15:14:22 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}