package com.liucan.boot.persist.mybatis.mode;

import java.time.LocalDateTime;

public class UserOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.user_id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.address
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.price
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.pay_type
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    private Short payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.create_time
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.update_time
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.id
     *
     * @return the value of user_order.id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.id
     *
     * @param id the value for user_order.id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.user_id
     *
     * @return the value of user_order.user_id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.user_id
     *
     * @param userId the value for user_order.user_id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_id
     *
     * @return the value of user_order.order_id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_id
     *
     * @param orderId the value for user_order.order_id
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.address
     *
     * @return the value of user_order.address
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.address
     *
     * @param address the value for user_order.address
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.price
     *
     * @return the value of user_order.price
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.price
     *
     * @param price the value for user_order.price
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.pay_type
     *
     * @return the value of user_order.pay_type
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public Short getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.pay_type
     *
     * @param payType the value for user_order.pay_type
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public void setPayType(Short payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.create_time
     *
     * @return the value of user_order.create_time
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.create_time
     *
     * @param createTime the value for user_order.create_time
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.update_time
     *
     * @return the value of user_order.update_time
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.update_time
     *
     * @param updateTime the value for user_order.update_time
     *
     * @mbg.generated Wed Jan 01 17:50:36 CST 2020
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}