/*
 * This file is generated by jOOQ.
 */
package com.liucan.boot.persist.jooq.javalearn;


import com.liucan.boot.persist.jooq.javalearn.tables.CommonUser;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class JavaLearn extends SchemaImpl {

    private static final long serialVersionUID = -1679016861;

    /**
     * The reference instance of <code>java_learn</code>
     */
    public static final JavaLearn JAVA_LEARN = new JavaLearn();

    /**
     * The table <code>java_learn.common_user</code>.
     */
    public final CommonUser COMMON_USER = com.liucan.boot.persist.jooq.javalearn.tables.CommonUser.COMMON_USER;

    /**
     * No further instances allowed
     */
    private JavaLearn() {
        super("java_learn", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                CommonUser.COMMON_USER);
    }
}
