/*
 * This file is generated by jOOQ.
 */
package com.liucan.boot.persist.jooq.javalearn;


import com.liucan.boot.persist.jooq.javalearn.tables.CommonUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in java_learn
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>java_learn.common_user</code>.
     */
    public static final CommonUser COMMON_USER = com.liucan.boot.persist.jooq.javalearn.tables.CommonUser.COMMON_USER;
}
